#ifndef BUS_H
#define BUS_H

#include "config.h"

// IO REGISTERS
#define P1_REG      0xFF00  // JOYPAD
#define SB_REG      0xFF01  // SERIAL TRANSFER DATA
#define SC_REG      0xFF02  // SERIAL TRANSFER CONTROL
#define DIV_REG     0xFF04  // DIVIDER REGISTER
#define TIMA_REG    0xFF05  // TIMER COUNTER
#define TMA_REG     0xFF06  // TIMER MODULO
#define TAC_REG     0xFF07  // TIMER CONTROL
#define IF_REG      0xFF0F  // INTERRUPT FLAG
#define NR10_REG    0xFF10  // SOUND MODE 1 REGISTER - SWEEP
#define NR11_REG    0xFF11  // SOUND MODE 1 REGISTER - LENGTH WAVE
#define NR12_REG    0xFF12  // SOUND MODE 1 REGISTER - ENVELOPE
#define NR13_REG    0xFF13  // SOUND MODE 1 REGISTER - FREQUENCY LO
#define NR14_REG    0xFF14  // SOUND MODE 1 REGISTER - FREQUENCY HI
#define NR21_REG    0xFF16  // SOUND MODE 2 REGISTER - LENGTH WAVE
#define NR22_REG    0xFF17  // SOUND MODE 2 REGISTER - ENVELOPE
#define NR23_REG    0xFF18  // SOUND MODE 2 REGISTER - FREQUENCY LO
#define NR24_REG    0xFF19  // SOUND MODE 2 REGISTER - FREQUENCY HI
#define NR30_REG    0xFF1A  // SOUND MODE 3 REGISTER - ON/OFF
#define NR31_REG    0xFF1B  // SOUND MODE 3 REGISTER - LENGTH
#define NR32_REG    0xFF1C  // SOUND MODE 3 REGISTER - OUTPUT LEVEL
#define NR33_REG    0xFF1D  // SOUND MODE 3 REGISTER - FREQUENCY LO
#define NR34_REG    0xFF1E  // SOUND MODE 3 REGISTER - FREQUENCY HI
#define NR41_REG    0xFF20  // SOUND MODE 4 REGISTER - LENGTH
#define NR42_REG    0xFF21  // SOUND MODE 4 REGISTER - ENVELOPE
#define NR43_REG    0xFF22  // SOUND MODE 4 REGISTER - POLYNOMIAL
#define NR44_REG    0xFF23  // SOUND MODE 4 REGISTER - COUNTER
#define NR50_REG    0xFF24  // CHANNEL CONTROL - ON/OFF - VOLUME
#define NR51_REG    0xFF25  // SELECTION OF SOUND OUTPUT TERMINAL
#define NR52_REG    0xFF26  // SOUND ON/OFF
#define LCDC_REG    0xFF40  // LCD CONTROL
#define STAT_REG    0xFF41  // LCDC STATUS
#define SCY_REG     0xFF42  // SCROLL Y
#define SCX_REG     0xFF43  // SCROLL X
#define LY_REG      0xFF44  // LCDC Y-COORDINATE
#define LYC_REG     0xFF45  // LY COMPARE
#define DMA_REG     0xFF46  // DMA TRANSFER AND START ADDRESS
#define BGP_REG     0xFF47  // BG PALETTE DATA
#define OBP0_REG    0xFF48  // OBJECT PALETTE 0 DATA
#define OBP1_REG    0xFF49  // OBJECT PALETTE 1 DATA
#define WY_REG      0xFF4A  // WINDOW Y POSITION
#define WX_REG      0xFF4B  // WINDOW X POSITION MINUS 7

u8 read_from_bus(u16 addr);
void write_to_bus(u16 addr, u8 val);

#endif