name: Build GBEmu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: clang
          - os: windows-latest
            cc: x86_64-w64-mingw32-gcc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SDL2 dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev

    - name: Setup SDL2 dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install sdl2

    - name: Setup SDL2 dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install mingw
        echo "SDL2 is expected in the repo's lib directory. Ensure the necessary .a files are present."

    - name: Build emulator
      env:
        CC: ${{ matrix.cc }}
      run: |
        make clean
        make all

    - name: Archive build artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: gb-emu-windows
        path: bin/gb-emu.exe

    - name: Archive build artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: gb-emu-linux
        path: bin/gb-emu

    - name: Archive build artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: gb-emu-macos
        path: bin/gb-emu
