name: Build GBEmu
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output: gb-emu
            artifact: gb-emu-linux
          - os: macos-latest
            output: gb-emu
            artifact: gb-emu-macos
          - os: windows-latest
            output: gb-emu.exe
            artifact: gb-emu-windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # SETUP SDL2 FOR LINUX AND MACOS
    - name: Install SDL2 (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
    
    - name: Install SDL2 (macOS)
      if: matrix.os == 'macos-latest'
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: latest
        sdl2-ttf: latest
        sdl2-image: 2.6.3
        sdl2-mixer: none
        sdl2-net: 2.2.0

    # BUILD USING MAKEFILE
    - name: Build
      shell: bash
      run: |
        make clean
        make all

    # UPLOAD ARTIFACTS
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: bin/${{ matrix.output }}

  # SEPARATE JOB FOR RELEASES
  release:
    needs: build
    
    # ONLY BUILD RELEASE WHEN WE PUSH A TAG
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gb-emu-linux/gb-emu
          gb-emu-macos/gb-emu
          gb-emu-windows/gb-emu.exe