name: Build GBEmu
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output: gb-emu
            artifact: gb-emu-linux
          - os: macos-latest
            output: gb-emu
            artifact: gb-emu-macos
          - os: windows-latest
            output: gb-emu.exe
            artifact: gb-emu-windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # SETUP SDL2 FOR LINUX AND MACOS
    - name: Install SDL2 (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev

    - name: Install SDL2 (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew update
        brew install sdl2

    # BUILD USING MAKEFILE
    - name: Build
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          eval "$(/opt/homebrew/bin/brew shellenv)"
        fi
        make clean
        make all

    # UPLOAD ARTIFACTS
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: bin/${{ matrix.output }}

  # SEPARATE JOB FOR RELEASES
  release:
    needs: build
    
    # ONLY BUILD RELEASE WHEN WE PUSH A TAG
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gb-emu-linux/gb-emu
          gb-emu-macos/gb-emu
          gb-emu-windows/gb-emu.exe